---
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
    - system:authenticated
  request: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLSVNEWm1BWWpVSG5zQWx0UVNKCkU0NXc5cXM4ZUJvM0FLd3dHWWFSb2VweWVlb3FRK1JrU3FWQ1FqRzhVVkRaYTNIN0pIRXdoZG5VampSR3NlZTgKcmE3SnhlcTFkdmRaZVpoZlVuMjMxNnBpRmc5WE9NWWcvZE53a0hVVmhIWDQ3UmNaakJuSUdtTVR6UHlCT3lqWQpKVElYNlp4MklUeWkrZUpxeGdqTUxqaEZxcGNBQ0lHZm9qY1l1ejZvalc0Z3hsZzRVRDVJNlBlYW55YUEvbTNvCkp1SXEycWNUcTQwRisrU0xDY0JZSVBDOHZKT1VyMEo0QTFuU3NqTU5JQVQvMWttZ2VXd2hrOEZ3TGlQMjh3cWMKb0ROQ1VhOHNrR29NRVplUm9mbU5RdEQ3UVAxSk1iNy9hTmRnWmc0NTg0WDIzL2ZSakhLUFg0S21HdFVmbi9SWgpQZnNDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFBZU5laU1vVi9iem5mZE5DZVJ6Qzloa3RwCkV5S2RlOEdhUndSbUJVZ0NtaHpyU2RrQmZuUGJJeVA3WWZIOWJlbnBEVUlVTHBoRWEvODVaOVVadVhSUExEYkIKL3JOcUplY3ZBb0M0RTIxakVtUGxMcVBFMWRCSW10RE9pVlRsMUg5bEU1VXJ5bE5wdXNrMlFRWXlXdnZQaHorVgpZd0xaWkVoUG9wY0l1L0tidFFYTlRIV1VSK1RPaEU5UzhwVnFFK2RZdmNtbTNyZnd0SDJyR0dqY2VpY2JEdlBiClJHWWRXZXEyV3h2RnJSMTBoekZFUDBsbzYwaGhkMlFwVDJYa3BwQlNuKzNYR2RxeDF2NFpxRTBMdW8xYk5xQXcKcWxmKzZNdFNCdXgyaVNGK3Zxb20zcDFyWERXdzFJbVpwNXRvb1ZubG1kQ2x1c2Y1d0h5SHFKbkhkSG9yCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo="
  usages:
    - digital signature
    - key encipherment
    - client auth
